#!/usr/bin/env python3
"""Validate the catalog and generate the dashboard pages.

Usage:
    python scripts/build_catalog.py          # validate + regenerate docs/catalog/*.md and catalog-info.yaml
    python scripts/build_catalog.py --check  # validate + fail if generated files are out of date (CI)
"""
from __future__ import annotations

import sys
from collections import Counter, defaultdict
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
CATALOG = ROOT / "catalog"
OUT = ROOT / "docs" / "catalog"
NS = "brianmichael.org/"

LIFECYCLES = ["idea", "design", "development", "testing", "deployed", "deprecated", "retired"]
KINDS_WITH_LIFECYCLE = {"Component", "API"}
REQUIRED_COMPONENT_ANNOTATIONS = ["language", "runtime", "repo", "priority"]
REQUIRED_DNS_ANNOTATIONS = ["domain", "registrar", "dns-host", "tls", "redirects-to", "renewal"]
DEFAULT_REF_KIND = {"dependsOn": None, "providesApis": "api", "consumesApis": "api",
                    "system": "system", "owner": "user"}

GENERATED_BANNER = "<!-- GENERATED by scripts/build_catalog.py; edit the YAML under catalog/, not this file -->\n"


# ------------------------------------------------------------------ loading
def load() -> list[dict]:
    entities = []
    for path in sorted(CATALOG.rglob("*.yaml")):
        for doc in yaml.safe_load_all(path.read_text()):
            if doc:
                doc["_path"] = path.relative_to(ROOT).as_posix()
                entities.append(doc)
    return entities


def key(kind: str, name: str) -> str:
    return f"{kind.lower()}:{name.lower()}"


def parse_ref(ref: str, default_kind: str | None) -> str:
    if ":" in ref:
        kind, name = ref.split(":", 1)
    elif default_kind:
        kind, name = default_kind, ref
    else:
        raise ValueError(f"reference '{ref}' needs an explicit kind (e.g. component:{ref})")
    return key(kind, name)


def a(entity: dict, name: str, default: str = "") -> str:
    return (entity["metadata"].get("annotations") or {}).get(NS + name, default)


# ------------------------------------------------------------------ validation
def validate(entities: list[dict]) -> list[str]:
    errors: list[str] = []
    index: dict[str, dict] = {}
    for e in entities:
        where = e["_path"]
        for field in ("apiVersion", "kind", "metadata", "spec"):
            if field not in e and not (field == "spec" and e.get("kind") == "Location"):
                errors.append(f"{where}: missing '{field}'")
        md = e.get("metadata", {})
        if not md.get("name"):
            errors.append(f"{where}: missing metadata.name")
            continue
        if not md.get("description"):
            errors.append(f"{where}: missing metadata.description")
        k = key(e["kind"], md["name"])
        if k in index:
            errors.append(f"{where}: duplicate {k} (also in {index[k]['_path']})")
        index[k] = e
        if Path(where).stem != md["name"]:
            errors.append(f"{where}: file name should match metadata.name '{md['name']}'")

        spec = e.get("spec", {})
        if e["kind"] in KINDS_WITH_LIFECYCLE and spec.get("lifecycle") not in LIFECYCLES:
            errors.append(f"{where}: lifecycle '{spec.get('lifecycle')}' not in {LIFECYCLES}")
        if e["kind"] == "Component":
            for req in REQUIRED_COMPONENT_ANNOTATIONS:
                if not a(e, req):
                    errors.append(f"{where}: missing annotation {NS}{req} (use 'tbd' if unknown)")
        if e["kind"] == "Resource" and spec.get("type") == "dns-zone":
            for req in REQUIRED_DNS_ANNOTATIONS:
                if not a(e, req):
                    errors.append(f"{where}: missing annotation {NS}{req} (use 'tbd' if unknown)")

    # references
    for e in entities:
        spec = e.get("spec", {})
        for field, default_kind in DEFAULT_REF_KIND.items():
            value = spec.get(field)
            if value is None:
                continue
            for ref in (value if isinstance(value, list) else [value]):
                try:
                    target = parse_ref(ref, default_kind)
                except ValueError as exc:
                    errors.append(f"{e['_path']}: {field}: {exc}")
                    continue
                if target not in index:
                    errors.append(f"{e['_path']}: {field} -> '{ref}' does not exist in the catalog")
    return errors


# ------------------------------------------------------------------ rendering helpers
BADGE = {"idea": "💡 idea", "design": "📐 design", "development": "🛠 dev", "testing": "🧪 test",
         "deployed": "✅ deployed", "deprecated": "⚠️ deprecated", "retired": "🪦 retired"}


def cell(v) -> str:
    if v in (None, "", []):
        return "—"
    if isinstance(v, list):
        v = ", ".join(v)
    v = str(v)
    return "<span class='tbd'>tbd</span>" if v == "tbd" else v.replace("|", "\\|")


def table(headers: list[str], rows: list[list]) -> str:
    out = ["| " + " | ".join(headers) + " |", "|" + "|".join("---" for _ in headers) + "|"]
    out += ["| " + " | ".join(cell(c) for c in r) + " |" for r in rows]
    return "\n".join(out) + "\n"


def short(ref: str) -> str:
    return ref.split(":", 1)[-1]


def mermaid_id(k: str) -> str:
    return k.replace(":", "__").replace("-", "_").replace(".", "_")


# ------------------------------------------------------------------ pages
def render_dashboard(entities: list[dict]) -> str:
    by_kind = defaultdict(list)
    for e in entities:
        by_kind[e["kind"]].append(e)
    comps = sorted(by_kind["Component"], key=lambda e: (e["spec"]["system"], e["metadata"]["name"]))
    apis = sorted(by_kind["API"], key=lambda e: (e["spec"]["system"], e["metadata"]["name"]))
    resources = [e for e in by_kind["Resource"] if e["spec"]["type"] != "dns-zone"]
    dns = sorted((e for e in by_kind["Resource"] if e["spec"]["type"] == "dns-zone"),
                 key=lambda e: a(e, "domain"))

    # reverse lookups
    consumers = defaultdict(list)
    for c in comps:
        for api in c["spec"].get("consumesApis", []):
            consumers[api].append(c["metadata"]["name"])
    providers = {api: c["metadata"]["name"] for c in comps for api in c["spec"].get("providesApis", [])}

    lc = Counter(c["spec"]["lifecycle"] for c in comps)
    summary = " · ".join(f"**{BADGE[l]}** {lc[l]}" for l in LIFECYCLES if lc[l])
    tbd = sum(1 for c in comps for n in REQUIRED_COMPONENT_ANNOTATIONS if a(c, n) == "tbd")

    md = [GENERATED_BANNER, "# Catalog dashboard\n",
          f"{len(comps)} components · {len(apis)} APIs · {len(resources)} resources · {len(dns)} DNS zones · "
          f"{tbd} open `tbd` fields on components\n",
          f"{summary}\n",
          "## Components\n",
          table(["System", "Component", "Type", "Status", "Priority", "Language", "Runtime", "Repo",
                 "Provides", "Consumes", "Depends on", "Description"],
                [[c["spec"]["system"], f"`{c['metadata']['name']}`", c["spec"]["type"],
                  BADGE[c["spec"]["lifecycle"]], a(c, "priority"), a(c, "language"), a(c, "runtime"),
                  a(c, "repo"), c["spec"].get("providesApis"), c["spec"].get("consumesApis"),
                  [short(d) for d in c["spec"].get("dependsOn", [])], c["metadata"]["description"]]
                 for c in comps]),
          "\n## APIs\n",
          table(["System", "API", "Type", "Status", "Provided by", "Consumed by", "Description"],
                [[p["spec"]["system"], f"`{p['metadata']['name']}`", p["spec"]["type"],
                  BADGE[p["spec"]["lifecycle"]], providers.get(p["metadata"]["name"]),
                  sorted(consumers.get(p["metadata"]["name"], [])), p["metadata"]["description"]]
                 for p in apis]),
          "\n## Resources\n",
          table(["System", "Resource", "Type", "Description"],
                [[r["spec"]["system"], f"`{r['metadata']['name']}`", r["spec"]["type"],
                  r["metadata"]["description"]]
                 for r in sorted(resources, key=lambda e: (e["spec"]["system"], e["metadata"]["name"]))]),
          "\n## DNS\n",
          table(["Domain", "System", "Registrar", "DNS host", "TLS", "Redirects to", "Serves", "Renewal"],
                [[a(d, "domain"), d["spec"]["system"], a(d, "registrar"), a(d, "dns-host"), a(d, "tls"),
                  a(d, "redirects-to"), a(d, "serves"), a(d, "renewal")] for d in dns]),
          ]
    return "\n".join(md)


def render_graphs(entities: list[dict]) -> str:
    index = {key(e["kind"], e["metadata"]["name"]): e for e in entities}
    systems = sorted(e["metadata"]["name"] for e in entities if e["kind"] == "System")
    providers = {key("api", api): key("component", e["metadata"]["name"])
                 for e in entities if e["kind"] == "Component"
                 for api in e["spec"].get("providesApis", [])}
    md = [GENERATED_BANNER, "# Dependency graphs\n",
          "Solid arrows: *consumes API of*. Dashed arrows: *depends on*. "
          "Nodes outside the system are shown with a dotted border.\n"]
    for system in systems:
        members = [e for e in entities if e["kind"] == "Component" and e["spec"]["system"] == system]
        if not members:
            continue
        title = index[key("system", system)]["metadata"].get("title", system)
        lines = ["```mermaid", "flowchart LR", "  classDef ext stroke-dasharray: 3 3,opacity:0.8;"]
        nodes, edges, external = set(), [], set()
        for c in members:
            src = key("component", c["metadata"]["name"])
            nodes.add(src)
            for api in c["spec"].get("consumesApis", []):
                tgt = providers.get(key("api", api))
                if tgt:
                    edges.append(f"  {mermaid_id(src)} -->|{api}| {mermaid_id(tgt)}")
                    nodes.add(tgt)
            for dep in c["spec"].get("dependsOn", []):
                tgt = parse_ref(dep, None)
                edges.append(f"  {mermaid_id(src)} -.-> {mermaid_id(tgt)}")
                nodes.add(tgt)
        for n in sorted(nodes):
            e = index[n]
            label = e["metadata"].get("title", e["metadata"]["name"])
            shape = f'[("{label}")]' if e["kind"] == "Resource" else f'["{label}"]'
            lines.append(f"  {mermaid_id(n)}{shape}")
            if e["spec"].get("system") != system:
                external.add(mermaid_id(n))
        lines += sorted(set(edges))
        if external:
            lines.append(f"  class {','.join(sorted(external))} ext;")
        lines.append("```")
        md.append(f"## {title}\n\n" + "\n".join(lines) + "\n")
    return "\n".join(md)


def render_location(entities: list[dict]) -> str:
    targets = sorted({"./" + e["_path"] for e in entities})
    loc = {"apiVersion": "backstage.io/v1alpha1", "kind": "Location",
           "metadata": {"name": "platform-catalog",
                        "description": "All catalog entities (generated by scripts/build_catalog.py)"},
           "spec": {"targets": targets}}
    return "# GENERATED by scripts/build_catalog.py\n" + yaml.safe_dump(loc, sort_keys=False)


# ------------------------------------------------------------------ main
def main() -> int:
    check = "--check" in sys.argv
    entities = load()
    errors = validate(entities)
    if errors:
        print(f"✗ {len(errors)} catalog error(s):")
        for err in errors:
            print("  -", err)
        return 1

    outputs = {
        OUT / "index.md": render_dashboard(entities),
        OUT / "graphs.md": render_graphs(entities),
        ROOT / "catalog-info.yaml": render_location(entities),
    }
    stale = []
    for path, content in outputs.items():
        if check:
            if not path.exists() or path.read_text() != content:
                stale.append(path.relative_to(ROOT).as_posix())
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    if stale:
        print("✗ generated files are out of date; run `make catalog` and commit:", *stale, sep="\n  - ")
        return 1
    print(f"✓ {len(entities)} entities valid" + ("" if check else "; generated files written"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
