apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: email-provider
  description: External email provider account - TBD
spec:
  type: third-party
  owner: user:brian
  system: infrastructure
