apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: slack-provider
  description: External slack provider account - TBD
spec:
  type: third-party
  owner: user:brian
  system: infrastructure
