apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: brianmichael-web
  description: brianmichael.org personal site
  annotations:
    brianmichael.org/language: tbd
    brianmichael.org/runtime: tbd
    brianmichael.org/repo: tbd
    brianmichael.org/priority: tbd
spec:
  type: website
  lifecycle: idea
  owner: user:brian
  system: brianmichael
  dependsOn:
  - resource:dns-brianmichael-org
