apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: starfireaviation-web
  description: Starfire Aviation LLC site
  annotations:
    brianmichael.org/language: tbd
    brianmichael.org/runtime: tbd
    brianmichael.org/repo: tbd
    brianmichael.org/priority: tbd
spec:
  type: website
  lifecycle: idea
  owner: user:brian
  system: starfireaviation
  dependsOn:
  - resource:dns-starfireaviation-com
