apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ttug-budget-service
  description: 'Budget planning: line items, scenarios, actuals'
  annotations:
    brianmichael.org/language: tbd
    brianmichael.org/runtime: tbd
    brianmichael.org/repo: tbd
    brianmichael.org/priority: tbd
spec:
  type: service
  lifecycle: idea
  owner: user:brian
  system: ttug
  providesApis:
  - budget-api
  consumesApis:
  - oidc
  - reports-api
  dependsOn:
  - resource:k3s-pi-cluster
  - resource:postgres
