apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ttug-documents-service
  description: Financial documents and historical documentation archive
  annotations:
    brianmichael.org/language: tbd
    brianmichael.org/runtime: tbd
    brianmichael.org/repo: tbd
    brianmichael.org/priority: tbd
spec:
  type: service
  lifecycle: idea
  owner: user:brian
  system: ttug
  providesApis:
  - documents-api
  consumesApis:
  - oidc
  - users-api
  dependsOn:
  - resource:k3s-pi-cluster
  - resource:postgres
  - resource:object-storage
